### ISSUE TITLE
Can Z2Pack calculate Chern number by interfacing with Wien2k ?

### ISSUE THREAD

**Issue by cz7989** [Z2PackDev/Z2Pack#106]
I am a Wien2k_18.2 user. I find that the interface wien2wannier (W2W) in the installation package could be used to generate the wannier90.mmn file. This file can be used as the input for Z2Pack calculating Chern number ? 
If this is true, how to set "kpt_fct" in the run.py ?
Thank you very much !

**Comment by greschd** [comment]
In principle, the wien2wannier interface _should_ work to compute Chern numbers with Z2Pack. However, I should note that I don't have experience in using this interface (and as such, haven't tested it).

The `kpt_fct` should produce the part of the input file (for Wien2k and / or wien2wannier) that determines the k-point path. You can find a short description [in the documentation](https://z2pack.greschd.ch/en/latest/tutorial/system.html#preparing-k-points-input), or use the [existing methods](https://github.com/Z2PackDev/Z2Pack/blob/dev/current/z2pack/fp/kpoint.py) as inspiration.

The main question in creating the `kpt_fct` is whether the wien2wannier interface allows for _any_ k-point path to be used, or if only regular meshes are allowed. For the former, you can use [`qe_explicit`](https://github.com/Z2PackDev/Z2Pack/blob/dev/current/z2pack/fp/kpoint.py#L91) and [`wannier90_full`](https://github.com/Z2PackDev/Z2Pack/blob/dev/current/z2pack/fp/kpoint.py#L147) as inspiration, for the latter [`vasp`](https://github.com/Z2PackDev/Z2Pack/blob/dev/current/z2pack/fp/kpoint.py#L157).

Since I haven't used Wien2k, I may be able to give more useful advice if you try implementing the `kpt_fct` and encounter a specific problem.

**Comment by cz7989** [comment]
Thank you very much for your reply ! 
According to your suggestions, I first determine that the wien2wannier interface can compute mmn for any kpath. Therefore, the only problem is how to generate kpoints files for Wien2k non-scf calculations. I try to write a MATLAB job, it can treat the file generated by "z2pack.fp.kpoint.wannier90_full" and write "build.klist_band".
Fortunately, it worked ! I run the example “Bi” and get the same results for VASP and QE (the two Z2 numbers are both zero). Here, I paste my "z2pack.fp.System" for reference:

system = z2pack.fp.System(
    input_files=["build.inwf", "build.win"],  # .inwf for wien2wannier
    kpt_fct=z2pack.fp.kpoint.wannier90_full,
    kpt_path="wannier_full.dat",
    command=(  "cd ../; "
               "prepare_w2wdir build; "  # input files for wien2k cal
               "cd build; "
               "matlab -nodisplay -nojvm -nosplash -nodesktop < ../gen_klist_band.m; "  # generate .klist_band
               "cat wannier_full.dat >> build.win; "
               "wannier_wien -pp build; "  # generate .nnkp for wien2wannier
               "../wien_parallel_gen.sh; "  # generate .machine* for wien parallel cal
               "x lapw1 -band -p; "  # wien non-scf cal
               "x lapwso -p; "
               "x w2w -so -up -p; "  # wien2wannier
               "x w2w -so -dn -p; "
               "x w2waddsp"),
    mmn_path='build.mmn'
)

Thanks again for your help !

**Comment by greschd** [comment]
Great to hear that this worked!

If you want to get around doing the round-trip to MATLAB, note that `kpt_fct` can be a list of Python functions, that will write to the corresponding files in a `kpt_path` list. As such, you could create a function to create the `.klist_band` file directly - that function doesn't need to be implemented inside Z2Pack, just adhere to the [the same interface](https://github.com/Z2PackDev/Z2Pack/blob/3dd808ec35514efe7f894252a1990152abd2323f/z2pack/fp/kpoint.py#L16-L24), i.e. it will get a list of k-points and needs to return the string to be appended to the file.

In any case, if the current solution works for you there's no problem in using that.
