### ISSUE TITLE
some corrections in fp examples files need!

### ISSUE THREAD

**Issue by abaradaran** [Z2PackDev/Z2Pack#78]
Dear Dominik Gresch

I meet some error when I wanted to run Bi_qe_6 example at Z2Pack-master-2.1.x, so I list them here:

in run.py At line 39

1. it seems you must alter "cell = ET.parse('scf/bi.save/data-file.xml')....." to "cell = ET.parse('scf/bi.save/data-file-schema.xml')...." because this file exist in this name at "scf/bi.save" folder,

2. In "data-file-schema.xml" does not any "DIRECT_LATTICE_VECTORS" object and exist more than one "CELL".

sincerely yours
A. Baradaran

**Comment by greschd** [comment]
Dear A. Baradaran,

This is an issue with the changed structure of the XML file between Quantum Espresso versions. On the dev/current branch, you can find different versions of the QE example for different code versions. Unfortunately this change hasn't made it into the master branch yet, since there was no particular reason to make a release of the Z2Pack software.

To always see the latest changes in the example files, it is a good idea to also check this branch (which can also be considered quite stable).

Best,
Dominik
